### ISSUE TITLE
Default styling for histoire menu/control tabs being overridden

### ISSUE THREAD

**Issue by jfitzsimmons2** [histoire-dev/histoire#66]
I'm willing to submit a PR if this is something that the team thinks should be addressed.

In my project, we have a CSS file that is brought in that has same shared styles across components. Currently, when that CSS is brought into histoire, it is overriding the histoire link styles on the sidebar and controls tabs. Is there a way to control the link styles for the sidebar and control tabs? This could be beneficial for future users looking to customize histoire.

In my histoire.setup
`import '@path/to/our/library/css.min.css';`

This CSS contains a rule
`a { color: blue }`

Which leads to some unwanted styling side effects within histoire

![image](https://user-images.githubusercontent.com/1531748/162974664-18909b15-9c9b-46c2-b470-32206efd40ea.png)
![image](https://user-images.githubusercontent.com/1531748/162974727-0f0f6e5b-20f7-4468-b816-419705e49531.png)

Some approaches could be:
1. Add a tailwind class to try to ensure the links are a certain color
2. Add a class to the containers for controls/story menus to allow targeting of the links within a custom histoire.css

**Comment by tillsanders** [comment]
I'm experiencing the same problem. I think this issue should be reopened as the root cause of the problem remains unsolved. 

I'm importing a stylesheet inside my setupFile (not inside histoire.config.js) and I'm using an iframe for my story. However, the style-tags are added both in the iframe and in the root document. 

On a side note: maybe a shadow dom can be considered for non-iframe stories.

**Comment by Akryum** [comment]
> However, the style-tags are added both in the iframe and in the root document.

This is expected.

**Comment by tillsanders** [comment]
Oh, I see. Personally, I wouldn't expect it to be that way. The naming `setupFile` suggests that it only 'sets the stage' for my story, not for histoire itself. Maybe it would make sense to have separate options for these.

Now, how can I make sure imported styles are not affecting the histoire user interface? Importing inside the story file has the same effect. I also cannot use scoping via selectors (e.g. a global class), because I don't have control over the library I'm importing.

Thank's for your help!

**Comment by tillsanders** [comment]
I found a workaround. I noticed that the title of the root document and the iframe document are different. Only the title of the root document contains `'Histoire'`. I use that to determine where the setupFile is being executed and only load the css files depending on that condition. This is a little bit of a dirty solution and I think there should be an official way to achieve this. Either with separate files or a global variable or something similar.

```javascript
// histoire-setup.js
const title = document.querySelector('title')?.text ?? ''
if (!title.includes('Histoire')) {
  // Only executed inside the iframe
  import('mylibrary/myLibrary.css')
}
```

**Comment by Akryum** [comment]
You workaround will work only if there is an iframe, but it's not always the case (with the grid layout for example).

**Comment by tillsanders** [comment]
Yes, that is a limitation. I don't think there is a way around it.

Do you think my general use case / issue should be addressed by a future release?

**Comment by tillsanders** [comment]
I noticed that my workaround is only working during dev mode, not in a static build. I tried to use another workaround based on `window.location.pathname` to determine wether the script is run inside the iframe. For some reason, that, too, doesn't work with a static build. 

Right now, I can use setupFile to customize the Histoire interface but I'm risking interfering with my stories. Or I can use setupFile to emulate an environment for my story but then I'm risking interfering with the Histoire interface. To me it looks like Histoire needs a better sandbox that will allow me to inject at least styling only into the story/sandbox. That would mean either using an iframe for every story or using a shadow DOM or a combination. Or am I missing something?

@Akryum You're building an amazing tool here and a great alternative to storybook. Thank you so much for your work. I would love to hear your thoughts on this!
